plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'com.google.devtools.ksp'
    id 'org.jetbrains.kotlin.plugin.serialization'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'com.google.gms.google-services'
    id 'com.google.firebase.crashlytics'
    id("com.google.android.libraries.mapsplatform.secrets-gradle-plugin")
}

android {
    namespace 'com.apollo9921.quizrise'
    compileSdk 35

    defaultConfig {
        applicationId "com.apollo9921.quizrise"
        minSdk 24
        targetSdk 35
        versionCode 14
        versionName "1.0.6"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary true
        }
    }

    def localProperties = new java.util.Properties()
    def localPropertiesFile = rootProject.file("local.properties")
    if (localPropertiesFile.exists()) {
        localProperties.load(localPropertiesFile.newInputStream())
    }

    buildTypes {
        debug {
            buildConfigField(
                    "String",
                    "GOOGLE_SERVER_CLIENT_ID",
                    "\"${localProperties.getProperty("GOOGLE_SERVER_CLIENT_ID") ?: ""}\""
            )
            buildConfigField(
                    "String",
                    "TRIVIA_API_KEY",
                    "\"${localProperties.getProperty("TRIVIA_API_KEY") ?: ""}\""
            )
            buildConfigField("String", "BASE_URL", "\"https://the-trivia-api.com/v2/\"")
        }

        release {
            buildConfigField(
                    "String",
                    "GOOGLE_SERVER_CLIENT_ID",
                    "\"${localProperties.getProperty("GOOGLE_SERVER_CLIENT_ID") ?: ""}\""
            )
            buildConfigField(
                    "String",
                    "TRIVIA_API_KEY",
                    "\"${localProperties.getProperty("TRIVIA_API_KEY") ?: ""}\""
            )
            buildConfigField("String", "BASE_URL", "\"https://the-trivia-api.com/v2/\"")

            minifyEnabled true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.getByName("debug")
        }
    }
    compileOptions {
        coreLibraryDesugaringEnabled true
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
    buildFeatures {
        compose true
        buildConfig true
    }
    packaging {
        resources {
            excludes.add("/META-INF/INDEX.LIST")
            excludes.add("/META-INF/DEPENDENCIES")
            excludes.add("/META-INF/LICENSE*")
            excludes.add("/META-INF/NOTICE*")
        }
    }
}

dependencies {
    def composeBom = platform('androidx.compose:compose-bom:2024.12.01')
    implementation composeBom
    androidTestImplementation composeBom

    // Core Android & Lifecycle (Actual latest versions)
    implementation 'androidx.core:core-ktx:1.15.0'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.8.7'
    implementation 'androidx.activity:activity-compose:1.9.3'

    // Compose Libraries (Managed by BOM)
    implementation 'androidx.compose.ui:ui'
    implementation 'androidx.compose.ui:ui-graphics'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    implementation 'androidx.compose.material3:material3'

    // Testing
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    debugImplementation 'androidx.compose.ui:ui-test-manifest'
    testImplementation("io.mockk:mockk:1.13.13")
    testImplementation "org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0"

    // Splash API
    implementation 'androidx.core:core-splashscreen:1.0.1'

    // Navigation (Latest stable is 2.8.5)
    implementation "androidx.navigation:navigation-compose:2.8.5"

    // Lottie Files
    implementation "com.airbnb.android:lottie-compose:6.6.0"

    // Data Store
    implementation "androidx.datastore:datastore-preferences:1.1.1"

    // Coil (Image Loading)
    implementation("io.coil-kt:coil-compose:2.7.0")

    // Room (Latest stable is 2.6.1)
    def room_version = "2.6.1"
    implementation "androidx.room:room-runtime:$room_version"
    ksp "androidx.room:room-compiler:$room_version"
    implementation "androidx.room:room-ktx:$room_version"
    androidTestImplementation "androidx.room:room-testing:$room_version"

    // Lifecycle components
    implementation "androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7"
    implementation "androidx.lifecycle:lifecycle-runtime-compose:2.8.7"

    // Coroutines
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0'

    // Ktor Client
    def ktor_version = "2.3.12"
    implementation "io.ktor:ktor-client-core:$ktor_version"
    implementation "io.ktor:ktor-client-android:$ktor_version"
    implementation "io.ktor:ktor-client-content-negotiation:$ktor_version"
    implementation "io.ktor:ktor-serialization-kotlinx-json:$ktor_version"
    implementation "io.ktor:ktor-client-logging:$ktor_version"

    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3"

    // DateTime Desugaring
    coreLibraryDesugaring "com.android.tools:desugar_jdk_libs:2.1.3"

    // Koin
    def koin_version = "4.0.0"
    implementation "io.insert-koin:koin-android:$koin_version"
    implementation "io.insert-koin:koin-androidx-compose:$koin_version"
    implementation "io.insert-koin:koin-androidx-navigation:$koin_version"

    // Firebase
    implementation platform('com.google.firebase:firebase-bom:33.7.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'
    implementation 'com.google.firebase:firebase-auth'
    implementation 'com.google.firebase:firebase-firestore'
    implementation "com.google.android.libraries.identity.googleid:googleid:1.1.1"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.9.0"
    implementation("com.google.firebase:firebase-functions-ktx:21.0.0")

    implementation "androidx.credentials:credentials:1.2.2"
    implementation "androidx.credentials:credentials-play-services-auth:1.2.2"

    // WorkManager
    implementation "androidx.work:work-runtime-ktx:2.9.0"

    // Icons
    implementation("androidx.compose.material:material-icons-extended")

    // Window Manager and Size Class for Foldables
    implementation "androidx.window:window:1.3.0"
    implementation "androidx.compose.material3:material3-window-size-class"

    // Browser Tabs
    implementation("androidx.browser:browser:1.8.0")

    implementation 'com.google.android.gms:play-services-auth:21.3.0'
}